[package]
name = "hello_world"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cubedesu"
path = "src/lib.rs"

[dependencies]
draw = "0.3.0"
