[package]
name = "cubedesu"
version = "0.1.0"
edition = "2018"

[lib]
name = "cubedesu"
path = "src/lib.rs"

[dependencies]
strum = "0.21"
strum_macros = "0.21"
macroquad = "0.3.10"

[dev-dependencies]
proptest = "1.0.0"